#!/usr/bin/env tsx
import fs from 'node:fs';
import path from 'node:path';
import { loadGameConfigFromFile } from '../core/configLoader';

const OUTPUT_FILE = path.resolve(process.cwd(), 'src', 'core', 'generatedGameConfig.ts');

function main(): void {
  const config = loadGameConfigFromFile();
  const content = `// AUTO-GENERATED by src/scripts/syncYamlConfig.ts. Do not edit by hand.\nimport type { GameConfig } from './gameConfigSchema';\n\nexport const GAME_CONFIG: GameConfig = ${JSON.stringify(config, null, 2)};\n`;
  fs.writeFileSync(OUTPUT_FILE, content, 'utf-8');
  console.log(`Synced YAML config to ${OUTPUT_FILE}`);
}

main();
