/**
 * Default commercial-safe progression theme for Merge Catalyst.
 *
 * Uses a generic material / rank ladder that is:
 *  - Instantly understandable (progression is obvious)
 *  - Broadly appealing (no niche branding)
 *  - Easy to localise (single short words)
 *  - Compatible with the discrete-doubling merge mechanic
 *
 * Internal numeric values (2 → 8192) are preserved unchanged in the
 * game engine.  This file only defines the player-facing shell.
 */

import { TileTheme } from './types';

export const defaultTheme: TileTheme = {
  id: 'progression',
  name: 'Progression',
  description: 'A generic material / rank ladder from Seed to Transcendent.',
  audience: 'general',
  readabilityScore: 9,
  iconStyleHint: 'emoji',
  entries: [
    {
      internalValue: 2,
      displayLabel: 'Seed',
      shortLabel: '◈',
      subtitle: 'The beginning',
      colorToken: '#d4e8c2',
      textColorToken: '#3a5a2a',
      iconToken: '🌱',
      rarityTag: 'common',
      progressionIndex: 0,
    },
    {
      internalValue: 4,
      displayLabel: 'Iron',
      shortLabel: 'Fe',
      subtitle: 'Solid foundation',
      colorToken: '#b0bec5',
      textColorToken: '#263238',
      iconToken: '🔩',
      rarityTag: 'common',
      progressionIndex: 1,
    },
    {
      internalValue: 8,
      displayLabel: 'Bronze',
      shortLabel: 'Br',
      subtitle: 'First refinement',
      colorToken: '#cd7f32',
      textColorToken: '#fff8f0',
      iconToken: '🥉',
      rarityTag: 'common',
      progressionIndex: 2,
    },
    {
      internalValue: 16,
      displayLabel: 'Silver',
      shortLabel: 'Ag',
      subtitle: 'Refined metal',
      colorToken: '#9e9e9e',
      textColorToken: '#f5f5f5',
      iconToken: '🥈',
      rarityTag: 'uncommon',
      progressionIndex: 3,
    },
    {
      internalValue: 32,
      displayLabel: 'Gold',
      shortLabel: 'Au',
      subtitle: 'Pure value',
      colorToken: '#ffc107',
      textColorToken: '#3e2800',
      iconToken: '🥇',
      rarityTag: 'uncommon',
      progressionIndex: 4,
    },
    {
      internalValue: 64,
      displayLabel: 'Platinum',
      shortLabel: 'Pt',
      subtitle: 'Beyond gold',
      colorToken: '#e0e0e0',
      textColorToken: '#1a1a2e',
      iconToken: '💎',
      rarityTag: 'rare',
      progressionIndex: 5,
    },
    {
      internalValue: 128,
      displayLabel: 'Emerald',
      shortLabel: 'Em',
      subtitle: 'Rare brilliance',
      colorToken: '#2e7d32',
      textColorToken: '#e8f5e9',
      iconToken: '💚',
      rarityTag: 'rare',
      progressionIndex: 6,
    },
    {
      internalValue: 256,
      displayLabel: 'Diamond',
      shortLabel: 'Dm',
      subtitle: 'Crystal clarity',
      colorToken: '#81d4fa',
      textColorToken: '#0d2233',
      iconToken: '🔷',
      rarityTag: 'epic',
      progressionIndex: 7,
    },
    {
      internalValue: 512,
      displayLabel: 'Master',
      shortLabel: 'Ms',
      subtitle: 'True mastery',
      colorToken: '#7c4dff',
      textColorToken: '#f3e5ff',
      iconToken: '⚜️',
      rarityTag: 'epic',
      progressionIndex: 8,
    },
    {
      internalValue: 1024,
      displayLabel: 'Apex',
      shortLabel: 'Ax',
      subtitle: 'Peak performance',
      colorToken: '#f44336',
      textColorToken: '#fff8f8',
      iconToken: '🔺',
      rarityTag: 'legendary',
      progressionIndex: 9,
    },
    {
      internalValue: 2048,
      displayLabel: 'Transcendent',
      shortLabel: 'Tr',
      subtitle: 'Beyond limits',
      colorToken: '#ff6d00',
      textColorToken: '#fff3e0',
      iconToken: '✨',
      rarityTag: 'legendary',
      progressionIndex: 10,
    },
    {
      internalValue: 4096,
      displayLabel: 'Eternal',
      shortLabel: 'Et',
      subtitle: 'Infinite cycle',
      colorToken: '#1a237e',
      textColorToken: '#e8eaf6',
      iconToken: '♾️',
      rarityTag: 'mythic',
      progressionIndex: 11,
    },
    {
      internalValue: 8192,
      displayLabel: 'Singularity',
      shortLabel: 'Sg',
      subtitle: 'One with all',
      colorToken: '#0d0d0d',
      textColorToken: '#ffe0ff',
      iconToken: '🌌',
      rarityTag: 'mythic',
      progressionIndex: 12,
    },
  ],
};
