import { CatalystDef, CatalystId } from './types';

export const CATALYST_DEFS: Record<CatalystId, CatalystDef> = {
  // ── Legacy ──────────────────────────────────────────────────────────────────
  corner_crown: {
    id: 'corner_crown',
    name: 'Corner Crown',
    description: 'Corner merges deal ×2 Output',
    rarity: 'rare',
    cost: 5,
    category: 'legacy',
    trigger: 'on_merge',
    effectParams: { multiplier: 2.0 },
    tags: ['corner', 'surge'],
    flavorText: 'Rule from the edges.',
    unlockCondition: 'Available from the start',
  },
  twin_burst: {
    id: 'twin_burst',
    name: 'Twin Burst',
    description: 'If ≥2 merges in one move, ×1.5 Output',
    rarity: 'common',
    cost: 3,
    category: 'legacy',
    trigger: 'on_merge',
    effectParams: { multiplier: 1.5, threshold: 2 },
    tags: ['combo', 'chain'],
    flavorText: 'Two at once — twice the reward.',
    unlockCondition: 'Available from the start',
  },
  lucky_seed: {
    id: 'lucky_seed',
    name: 'Lucky Seed',
    description: 'Spawn probability: 75% "2" / 25% "4"',
    rarity: 'common',
    cost: 3,
    category: 'legacy',
    trigger: 'on_spawn',
    effectParams: { probability: 0.75 },
    tags: ['spawn', 'economy'],
    flavorText: 'Plant low, harvest high.',
    unlockCondition: 'Available from the start',
  },
  bankers_edge: {
    id: 'bankers_edge',
    name: "Banker's Edge",
    description: '+2 Energy after phase clear',
    rarity: 'common',
    cost: 3,
    category: 'legacy',
    trigger: 'on_phase_clear',
    effectParams: { energyBonus: 2 },
    tags: ['energy', 'economy'],
    flavorText: 'Every cleared phase is a deposit.',
    unlockCondition: 'Available from the start',
  },
  reserve: {
    id: 'reserve',
    name: 'Reserve',
    description: 'Each unused step gives +20 Output on phase clear',
    rarity: 'rare',
    cost: 5,
    category: 'legacy',
    trigger: 'on_phase_clear',
    effectParams: { flatBonus: 20 },
    tags: ['economy', 'control'],
    flavorText: 'Patience is its own multiplier.',
    unlockCondition: 'Available from the start',
  },
  frozen_cell: {
    id: 'frozen_cell',
    name: 'Frozen Cell',
    description: 'One cell cannot spawn tiles',
    rarity: 'common',
    cost: 3,
    category: 'legacy',
    trigger: 'passive',
    effectParams: {},
    tags: ['board', 'control'],
    flavorText: 'Hold one corner sacred.',
    unlockCondition: 'Available from the start',
  },
  combo_wire: {
    id: 'combo_wire',
    name: 'Combo Wire',
    description: '3 consecutive scoring moves → ×1.3 Output',
    rarity: 'rare',
    cost: 5,
    category: 'legacy',
    trigger: 'on_move',
    effectParams: { multiplier: 1.3, period: 3 },
    tags: ['combo', 'chain'],
    flavorText: 'Keep the current flowing.',
    unlockCondition: 'Available from the start',
  },
  high_tribute: {
    id: 'high_tribute',
    name: 'High Tribute',
    description: 'If highest tile merges → ×1.4 Output',
    rarity: 'rare',
    cost: 5,
    category: 'legacy',
    trigger: 'on_merge',
    effectParams: { multiplier: 1.4 },
    tags: ['surge', 'combo'],
    flavorText: 'The pinnacle pays its own tribute.',
    unlockCondition: 'Available from the start',
  },

  // ── Amplifier ────────────────────────────────────────────────────────────────
  empty_amplifier: {
    id: 'empty_amplifier',
    name: 'Empty Amplifier',
    description: '+0.05 Output multiplier per empty cell on the board',
    rarity: 'common',
    cost: 3,
    category: 'amplifier',
    trigger: 'on_merge',
    effectParams: { multiplier: 0.05 },
    tags: ['board', 'surge'],
    flavorText: 'Silence amplifies signal.',
    unlockCondition: 'Unlock with 15 Core Shards',
  },
  chain_reactor: {
    id: 'chain_reactor',
    name: 'Chain Reactor',
    description: 'Chain multiplier grows by ×0.2 per merge beyond the first',
    rarity: 'rare',
    cost: 5,
    category: 'amplifier',
    trigger: 'on_merge',
    effectParams: { multiplier: 0.2 },
    tags: ['chain', 'surge'],
    flavorText: 'One reaction feeds the next.',
    unlockCondition: 'Unlock with 25 Core Shards',
  },
  echo_multiplier: {
    id: 'echo_multiplier',
    name: 'Echo Multiplier',
    description: 'Carry 20% of last move\'s Output into this move as a bonus',
    rarity: 'rare',
    cost: 5,
    category: 'amplifier',
    trigger: 'on_merge',
    effectParams: { multiplier: 0.2 },
    tags: ['echo', 'chain'],
    flavorText: 'Your last move still resonates.',
    unlockCondition: 'Unlock with 25 Core Shards',
  },
  threshold_surge: {
    id: 'threshold_surge',
    name: 'Threshold Surge',
    description: 'If base Output exceeds 30, apply ×1.5 bonus',
    rarity: 'rare',
    cost: 5,
    category: 'amplifier',
    trigger: 'on_merge',
    effectParams: { multiplier: 1.5, threshold: 30 },
    tags: ['surge', 'risk'],
    flavorText: 'Break the ceiling, claim the bonus.',
    unlockCondition: 'Unlock with 25 Core Shards',
  },
  phase_resonance: {
    id: 'phase_resonance',
    name: 'Phase Resonance',
    description: 'Output multiplier scales with current phase index (×0.1 per phase)',
    rarity: 'epic',
    cost: 7,
    category: 'amplifier',
    trigger: 'on_merge',
    effectParams: { multiplier: 0.1 },
    tags: ['phase', 'surge'],
    flavorText: 'The deeper in, the louder the signal.',
    unlockCondition: 'Unlock with 40 Core Shards',
  },

  // ── Stabilizer ───────────────────────────────────────────────────────────────
  gravity_well: {
    id: 'gravity_well',
    name: 'Gravity Well',
    description: 'Corner cells gain a bias making high tiles gravitate there; ×1.1 if merge at corner',
    rarity: 'common',
    cost: 3,
    category: 'stabilizer',
    trigger: 'on_merge',
    effectParams: { multiplier: 1.1 },
    tags: ['corner', 'board'],
    flavorText: 'High-value tiles seek the edges.',
    unlockCondition: 'Unlock with 15 Core Shards',
  },
  soft_reset: {
    id: 'soft_reset',
    name: 'Soft Reset',
    description: 'Remove the lowest-value tile from the board once per run',
    rarity: 'rare',
    cost: 5,
    category: 'stabilizer',
    trigger: 'passive',
    effectParams: {},
    tags: ['board', 'control'],
    flavorText: 'Sometimes less is more space.',
    unlockCondition: 'Unlock with 25 Core Shards',
  },
  buffer_zone: {
    id: 'buffer_zone',
    name: 'Buffer Zone',
    description: 'The top row is blocked from receiving spawned tiles',
    rarity: 'common',
    cost: 3,
    category: 'stabilizer',
    trigger: 'on_spawn',
    effectParams: {},
    tags: ['board', 'spawn', 'control'],
    flavorText: 'Keep one row free to breathe.',
    unlockCondition: 'Unlock with 15 Core Shards',
  },
  merge_shield: {
    id: 'merge_shield',
    name: 'Merge Shield',
    description: 'Absorbs one phase failure every 5 moves',
    rarity: 'epic',
    cost: 7,
    category: 'stabilizer',
    trigger: 'passive',
    effectParams: { period: 5 },
    tags: ['shield', 'risk'],
    flavorText: 'The run continues — for now.',
    unlockCondition: 'Unlock with 40 Core Shards',
  },
  stability_field: {
    id: 'stability_field',
    name: 'Stability Field',
    description: '3 consecutive valid moves grant ×1.2 Output until a miss',
    rarity: 'rare',
    cost: 5,
    category: 'stabilizer',
    trigger: 'on_move',
    effectParams: { multiplier: 1.2, period: 3 },
    tags: ['combo', 'shield'],
    flavorText: 'Steady hands, steady gains.',
    unlockCondition: 'Unlock with 25 Core Shards',
  },

  // ── Generator ────────────────────────────────────────────────────────────────
  double_spawn: {
    id: 'double_spawn',
    name: 'Double Spawn',
    description: '25% chance to spawn 2 tiles instead of 1 after a move',
    rarity: 'common',
    cost: 3,
    category: 'generator',
    trigger: 'on_spawn',
    effectParams: { probability: 0.25 },
    tags: ['spawn', 'risk'],
    flavorText: 'More tiles, more chances.',
    unlockCondition: 'Unlock with 15 Core Shards',
  },
  rich_merge: {
    id: 'rich_merge',
    name: 'Rich Merge',
    description: 'Gain +1 Energy for each merge in a move',
    rarity: 'rare',
    cost: 5,
    category: 'generator',
    trigger: 'on_merge',
    effectParams: { energyBonus: 1 },
    tags: ['energy', 'economy', 'chain'],
    flavorText: 'Every merge is a payday.',
    unlockCondition: 'Unlock with 25 Core Shards',
  },
  catalyst_echo: {
    id: 'catalyst_echo',
    name: 'Catalyst Echo',
    description: 'Duplicate the effect of the weakest active catalyst once per phase',
    rarity: 'epic',
    cost: 7,
    category: 'generator',
    trigger: 'on_phase_clear',
    effectParams: {},
    tags: ['echo', 'phase'],
    flavorText: 'Even weak signals can resonate.',
    unlockCondition: 'Unlock with 40 Core Shards',
  },
  energy_loop: {
    id: 'energy_loop',
    name: 'Energy Loop',
    description: '10% of Output from each move converts to Energy',
    rarity: 'rare',
    cost: 5,
    category: 'generator',
    trigger: 'on_merge',
    effectParams: { multiplier: 0.1 },
    tags: ['energy', 'economy'],
    flavorText: 'Output fuels the forge.',
    unlockCondition: 'Unlock with 25 Core Shards',
  },
  reserve_bank: {
    id: 'reserve_bank',
    name: 'Reserve Bank',
    description: 'Each step taken converts +1 Energy at phase clear',
    rarity: 'common',
    cost: 3,
    category: 'generator',
    trigger: 'on_phase_clear',
    effectParams: { energyBonus: 1 },
    tags: ['energy', 'economy'],
    flavorText: 'Every step earns its keep.',
    unlockCondition: 'Unlock with 15 Core Shards',
  },

  // ── Modifier ─────────────────────────────────────────────────────────────────
  diagonal_merge: {
    id: 'diagonal_merge',
    name: 'Diagonal Merge',
    description: 'Every 4th move counts diagonal adjacency for merge bonus (×1.2)',
    rarity: 'epic',
    cost: 7,
    category: 'modifier',
    trigger: 'on_move',
    effectParams: { multiplier: 1.2, period: 4 },
    tags: ['board', 'combo'],
    flavorText: 'Think sideways.',
    unlockCondition: 'Unlock with 40 Core Shards',
  },
  split_protocol: {
    id: 'split_protocol',
    name: 'Split Protocol',
    description: 'Once per phase, split the highest tile into two tiles of half value',
    rarity: 'epic',
    cost: 7,
    category: 'modifier',
    trigger: 'on_phase_clear',
    effectParams: {},
    tags: ['board', 'risk', 'phase'],
    flavorText: 'Division creates opportunity.',
    unlockCondition: 'Unlock with 40 Core Shards',
  },
  inversion_field: {
    id: 'inversion_field',
    name: 'Inversion Field',
    description: 'Lowest-value merges score first, inverting the usual priority; ×1.15 Output',
    rarity: 'rare',
    cost: 5,
    category: 'modifier',
    trigger: 'on_merge',
    effectParams: { multiplier: 1.15 },
    tags: ['board', 'surge'],
    flavorText: 'Small tiles, big potential.',
    unlockCondition: 'Unlock with 25 Core Shards',
  },
  overflow_grid: {
    id: 'overflow_grid',
    name: 'Overflow Grid',
    description: 'Once per run, grant +2 virtual empty cells for one move',
    rarity: 'epic',
    cost: 7,
    category: 'modifier',
    trigger: 'on_move',
    effectParams: { flatBonus: 2 },
    tags: ['board', 'risk'],
    flavorText: 'Bend the grid when space runs out.',
    unlockCondition: 'Unlock with 40 Core Shards',
  },
  delay_spawn: {
    id: 'delay_spawn',
    name: 'Delay Spawn',
    description: 'Skip tile spawn this move; the next move spawns 2 tiles instead',
    rarity: 'rare',
    cost: 5,
    category: 'modifier',
    trigger: 'on_spawn',
    effectParams: {},
    tags: ['spawn', 'control', 'risk'],
    flavorText: 'Pause before the flood.',
    unlockCondition: 'Unlock with 25 Core Shards',
  },
  anomaly_sync: {
    id: 'anomaly_sync',
    name: 'Anomaly Sync',
    description: 'Gain ×1.3 Output multiplier whenever an anomaly effect triggers',
    rarity: 'epic',
    cost: 7,
    category: 'modifier',
    trigger: 'on_anomaly',
    effectParams: { multiplier: 1.3 },
    tags: ['anomaly', 'risk', 'surge'],
    flavorText: 'Chaos is just free multiplier.',
    unlockCondition: 'Unlock with 40 Core Shards',
  },
};

export const ALL_CATALYSTS = Object.values(CATALYST_DEFS);

export function getRandomCatalystOffers(
  exclude: CatalystId[],
  count: number,
  rng: () => number
): CatalystDef[] {
  const available = ALL_CATALYSTS.filter(c => !exclude.includes(c.id));
  const shuffled = [...available].sort(() => rng() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
